name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "43 8 * * 0"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: false
          disk-cache: ${{ github.workflow }}
          repository-cache: false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: "bazel test //..."
      - name: Build
        run: "cd integration && bazel build //... --sandbox_debug --subcommands && cat bazel-bin/verilog/lib.v"

